import streamlit as st

st.title("6460 Final Portolio Project - Motivational Revamp of Duolingo")
st.subheader('Aditya Kesavan with Team Members: Sarang, Ritika, Amirita, Divyaansh')

st.header("Background & Problem")
st.write("""As part of the CS 6460 course, Dr. Judith Uchidiuno assigned an in-depth project focused on enhancing educational technology applications with a primary emphasis on motivation. Motivation is critically important in the educational process, impacting both the intensity and persistence of a learner's engagement with a tool. Research from texts like "How Learning Works" and "How People Learn," underscores that motivation's role extends beyond merely attracting users—it is crucial in maintaining their engagement over time. Motivated learners are more inclined to tackle challenging tasks, utilize cognitive strategies, and achieve superior educational outcomes. This underscores the necessity of designing learning technologies that not only capture but sustain user engagement, interest, and effort.""")
st.header("Our Changes")
st.write("""We aimed to imrpove Duolingo. We understood that sustaining user motivation in digital learning environments is complex and influenced by a variety of factors, including user goals, content relevance, and personalization of the learning experience. So our project proposal iteratively refined five features aimed at boosting motivation.""")
st.subheader('1. Slang Integration')
st.write("Language learning is not only about formal structures but also cultural nuances, so we introduced slang integration in Duolingo. This feature allows learners to access informal language uses specific to cultures they are interested in, thereby making the learning process more comprehensive and relatable.")
st.image('Slang.png')
st.subheader("2. Music Integration")
st.write("Music is a powerful tool used for learning due to its rhythmic and lyrical properties. Integrating music into language lessons, we aimed to make learning more enjoyable, thereby enhancing intrinsic motivation through engaging content that resonates with peoples interests.")
st.image('Music.jpg')
st.subheader("3. Personalized Leaarning Experience")
st.write("Leveraged AI algorithms, we created customized lesson plans that adapt to individual learning needs/preferences. By focusing on personal weaknesses and interests, this feature aims to make learning more personally relevant, which is critical for sustaining long-term motivation.")
st.image('Focus.png')
st.subheader("4. Social Progress")
st.write("Incorporating social elements into the learning process, this feature allows users to connect with friends, see their progress, and engage in friendly challenges. It taps into extrinsic motivation by fostering a sense of community and friendly competition.")
st.image('Social.png')
st.subheader("5. Video-Based Learning")
st.write("Incorporating video content, this features, provides context-rich learning scenarios that enhance language comprehension and speaking skills. Using media that learners are already familiar with, this feature will increase engagement and make learning feel less like a chore.")
st.image('VBLearning.jpg')
st.header("Outcome")
st.write("These 5 features were developed with the goal of addressing specific motivational barriers identified through user research and testing. By focusing on these five features, our project aimed to transform the educational experience into one that is effective in fostering sustained learner motivation.")
st.image('Fullflow.jpg')